metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.template.settings:
  index.number_of_shards: 1
  index.codec: best_compression

setup.kibana:
  host: "elastic0:5601"

output.elasticsearch:
  hosts: ["http://elastic0:9200"]

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~

setup.ilm.enabled: false